[theme]
base = "dark"
primaryColor = "#055858ff"
backgroundColor = "transparent"
secondaryBackgroundColor = "rgba(244, 255, 255, 0.1)"
textColor = "#FAFAFA"
font = "sans serif"

[theme.sidebar]
backgroundColor="transparent"
secondaryBackgroundColor="#00ccffff"
borderColor="black"
